spring.application.name=jpa
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/bookstore_jpa
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true